baseURL = "https://frapaparatto.dev"
title = "Francesco Paparatto"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Personal blog about software, tech, and things I find interesting."
  copyright = "Copyright © 2025 Francesco Paparatto"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  unsafe = true
